name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  plan:
    name: CI Plan
    runs-on: ubuntu-latest
    outputs:
      tinx_outputs: ${{ steps.tinx-plan.outputs.outputs-json }}
    steps:
      - uses: actions/checkout@v4

      - id: tinx-plan
        uses: sourceplane/tinx-action@v2
        with:
          providers: |
            sourceplane/lite-ci:v0.2.25 as lite-ci
          run: |
            tinx -- lite-ci plan \
            --config-dir ~/.tinx/providers/sourceplane/lite-ci/v0.2.25/assets/config/compositions \
            --view dag 
          artifacts: plan.json
      - name: run plan
        run: tinx -- lite-ci run -x --plan plan.json --job-id "common-services@production.deploy"




